### PR TITLE
Added a timeline view to the scoreboard

### PR DESCRIPTION
**Pull request by cgtboy1988**

### CODE REVIEW

**Comment by nealey** [comment]
Please make the following changes:

- Create two new files:
  - `scoreboard-llnl.html` (or better yet, a name describing how it's different, my mind is shot right now) that renders just your scoreboard, no interactive buttons.
  - `scoreboard-proj.html` which, in an iFrame or whatever makes more sense, rotates through both scoreboards automatically. This is what we'll run on the projector.

**Comment by cgtboy1988** [comment]
Made the updates.  There are now two -llnl scoreboard pages (one for the "All Points" view and one for the "Timeline" view).  These operate on a different .js file from the regular scoreboard (I was apparently making changes to the older scoreboard.js file, before the animation was added, and merging the newer animated .js with the -llnl.js will be a pain and can be done later).  The scoreboard-proj.html page cycles through all three scoreboards on a timeout with an iFrame.  I set the timeout to 25000, but this can easily be changed as desired.  I will plan to make the timeout passable via URL arguments (or even a UI element) sometime if we want it adjustable.

**Comment by nealey** [comment]
Looks good. I want to run it once but can't see anything that would keep this from merging. Thanks

**Comment by cgtboy1988** [comment]
Great! I tested with the sample points.json. Later today I'll try to test with the base case (0 teams/points) just to double check the scoreboard views don't break for that also.

**Comment by pi-rho** [comment]
Popping in for Neale ... 

- llnl-all - if the number of categories is greater than 10, you run out of colors. I suggest adding modulo math to access the color palette (i.e. `colors[i % numcolors]`) so the palette will roll

- llnl-timeline - The graph needs to have a flexible width. It seems to be fixed at 800px or so.

**Comment by cgtboy1988** [comment]
I'll get some changes pushed out in the next few hours to fix these things. I have already made changes, but am about to have a meeting on some other stuff and want to test before pushing. Also, I want to clarify on two things so I can get the details right.

Question on the llnl-all: How many categories do we expect to have? I have changed it so that the current colors repeat after 10, but if we expect to have more than 10 categories I can also look for a bigger color scale so that we can support more categories uniquely.

Quick comment on the timeline: The previous iteration scaled until rendering-if the page was loaded, it would render the visualization to 80% of the width of the window. I have changed it so that it refreshes the data and redraws upon window resize, but should the graph itself be 100% width also? If so, I'll make that change before pushing.

**Comment by cgtboy1988** [comment]
I just reread the part about the timeline. Could you send me a points.json which generates this behavior so I can easily reproduce and fix?

**Comment by cgtboy1988** [comment]
Just tested and pushed some changes.  I added a modulo on the "all" color selection, and made a window resize refresh the timeline.  I also relocated the legend on the timeline in order to keep it out of the graph.  Please let me know if this solves the problems.

**Comment by pi-rho** [comment]
Looks good over here. Merge request approved. :)

**Pull request merged**
